version: "2"

services:
  web:
    build: .
    command: >
      gunicorn --paste development.ini -b 0.0.0.0:6543
    env_file:
      - ".env"
    ports:
      - "6543:6543"
    volumes:
      - ".:/app"
