GET http://localhost:6543/counterparty/1
Content-Type: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJhZG1pbnMiXSwidXNlcm5hbWUiOiJhZG1pbiIsInN1YiI6MSwiaWF0IjoxNTIzMTQ0MDMxfQ.V2wbKVh_xxJU1J4jtOHp7Mby0bB3JW6UfDpCCWHZD1EBesKQURtiSGwEEGwS83RRwMQcBjRFu0wTDYdg9Kqh_w
###

GET http://localhost:6543/counterparty/
Content-Type: application/json

###
POST http://localhost:6543/counterparty/
Content-Type: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJhZG1pbnMiXSwidXNlcm5hbWUiOiJhZG1pbiIsInN1YiI6MSwiaWF0IjoxNTIzMTQyNTM5fQ.xO2xpK0qpk5k_3hGN1FWedI3kz_vyLPd8KYBLR7l23nlIm-Yd5m85CgblwXsFTdD1fP7wHjri0hUUhOK695wFw

{
    "name": "Company 991",
    "eik_egn": "f08p87771b8"
}

###
POST http://localhost:6543/counterparty/
Content-Type: application/json

{
    "name": "Company 21",
    "eik_egn": "m88119780"
}

###
PUT http://localhost:6543/counterparty/5
Content-Type: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJhZG1pbnMiXSwidXNlcm5hbWUiOiJhZG1pbiIsInN1YiI6MSwiaWF0IjoxNTIyNTM3NDc3fQ.ZuX37v7kQWYc72EllRPzpIA12DyRa_e3E3q9n6i2K8w9cRmxguZAcvzJu3Ekrz_VCX2krWitgVgqJZmhU6Js7g

{
    "name": "Company 3000",
    "eik_egn": "188456798"
}

###

DELETE http://localhost:6543/counterparty/5
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJhZG1pbnMiXSwidXNlcm5hbWUiOiJhZG1pbiIsInN1YiI6MSwiaWF0IjoxNTIyNTM3NDc3fQ.ZuX37v7kQWYc72EllRPzpIA12DyRa_e3E3q9n6i2K8w9cRmxguZAcvzJu3Ekrz_VCX2krWitgVgqJZmhU6Js7g


###
POST http://localhost:6543/user/login
Content-Type: application/json

{
    "identity": "admin",
    "password": "password"
}

###
POST http://localhost:6543/user/signup
Content-Type: application/json

{
    "username": "user",
    "email": "user4@local.host",
    "password": "password"
}

###
POST http://localhost:6543/user/login
Content-Type: application/json

{
    "identity": "user",
    "password": "password"
}
###
http://localhost:6543/user/3
Content-Type: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJhZG1pbnMiXSwidXNlcm5hbWUiOiJhZG1pbiIsInN1YiI6MSwiaWF0IjoxNTIyNTM3NDc3fQ.ZuX37v7kQWYc72EllRPzpIA12DyRa_e3E3q9n6i2K8w9cRmxguZAcvzJu3Ekrz_VCX2krWitgVgqJZmhU6Js7g
