GET http://localhost:6543/counterparty/
Content-Type: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJhZG1pbiJdLCJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoxLCJpYXQiOjE1MjIyNzc2ODZ9.DoUmGxYCDEcJsd1eQPOcUj6XDunuqiRT9vG3bfNQAIKcy2tZwtSYDm0n2IK6GY3ATa9K7i-kXSUaSWf99BK9vA
###

GET http://localhost:6543/counterparty/101

###
POST http://localhost:6543/counterparty/
Content-Type: application/json

{
    "name": "Company 991",
    "eik_egn": "888777a40"
}

###
POST http://localhost:6543/counterparty/
Content-Type: application/json

{
    "name": "Company 21",
    "eik_egn": "888119780"
}

###
PUT http://localhost:6543/counterparty/4
Content-Type: application/json

{
    "name": "Company 3000",
    "eik_egn": "188456798"
}

###

DELETE http://localhost:6543/counterparty/8


###
POST http://localhost:6543/login
Content-Type: application/json

{
    "login": "admin",
    "password": "1234"
}
